version: '3.1'
services:

  stats-server:
    build: ./stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db

    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    container_name: ewm-services
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - stats-server.url=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
