version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=ewmUser
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewmUser
      - POSTGRES_PASSWORD=root

  stats-server:
    build: ./stat-service
    container_name: ewm-stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - dbUser=ewmUser
      - dbPass=root
      - EWM_FEIGN_CLIENT_URL=http://ewm-service:8080
  ewm-service:
    build: ./main-service
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - dbUser=ewmUser
      - dbPass=root
      - EWM_STATS_SERVER_URL=http://server:9090
      - EWM_FEIGN_CLIENT_URL=http://stats-server:9090
